version: '3'
services:
  apollo-router-custom-image:
    container_name: apollo-router-custom-image
    build: ./router/custom-image
    volumes:
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router/custom-image/acme_router.yaml:/dist/config/router.yaml
    command: [ "-c", "config/router.yaml", "-s", "schema/supergraph.graphql", "--log", "trace" ]
    ports:
      - "4000:4000"
  products:
    container_name: products
    build: ./subgraphs/products
  inventory:
    container_name: inventory
    build: ./subgraphs/inventory
  users:
    container_name: users
    build: ./subgraphs/users
  pandas:
    container_name: pandas
    build: ./subgraphs/pandas
  reviews:
    container_name: reviews
    build: ./subgraphs/reviews
