version: '3'
services:
  apollo-router:
    container_name: apollo-router
    build: ./router/custom-image
    volumes:
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router.yaml:/dist/config/router.yaml
    command: [ "-c", "config/router.yaml", "-s", "schema/supergraph.graphql", "--log", "info" ]
    ports:
      - "4000:4000"
  products:
    container_name: products
    build: ./subgraphs/products
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  inventory:
    container_name: inventory
    build: ./subgraphs/inventory
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  users:
    container_name: users
    build: ./subgraphs/users
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  pandas:
    container_name: pandas
    build: ./subgraphs/pandas
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.55.0
    command: ["--config=/conf/collector-config.yml"]
    volumes:
      - ./opentelemetry/collector-config.yml:/conf/collector-config.yml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    depends_on:
      - zipkin
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23.18
    ports:
      - "9411:9411"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    volumes:
      - ./opentelemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
