version: '3'
services:
  apollo-gateway:
    container_name: apollo-gateway
    build: ./gateway
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
      - APOLLO_OTEL_EXPORTER_TYPE=zipkin
      - APOLLO_OTEL_EXPORTER_HOST=zipkin
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "4000:4000"
    depends_on:
      - zipkin
  products:
    container_name: products
    build: ./subgraphs/products
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=zipkin
      - APOLLO_OTEL_EXPORTER_HOST=zipkin
  inventory:
    container_name: inventory
    build: ./subgraphs/inventory
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=zipkin
      - APOLLO_OTEL_EXPORTER_HOST=zipkin
  users:
    container_name: users
    build: ./subgraphs/users
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=zipkin
      - APOLLO_OTEL_EXPORTER_HOST=zipkin
  pandas:
    container_name: pandas
    build: ./subgraphs/pandas
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23.16
    ports:
      - "9411:9411"
