[package]
name = "acme_router"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
apollo-router = "1.18.1"
async-trait = "0.1.68"
futures = "0.3.28"
http = "0.2.9"
schemars = "0.8.12"
serde = "1.0.163"
serde_json = "1.0.96"
tokio = "1.28.1"
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1"
