[package]
name = "acme_router"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
apollo-router = "1.24.0"
async-trait = "0.1.71"
futures = "0.3.28"
http = "0.2.9"
schemars = "0.8.12"
serde = "1.0.173"
serde_json = "1.0.103"
tokio = "1.29.1"
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1"
