[package]
name = "acme_router"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
apollo-router = "1.35.0"
async-trait = "0.1.74"
futures = "0.3.29"
http = "0.2.11"
schemars = "0.8.16"
serde = "1.0.193"
serde_json = "1.0.108"
tokio = "1.35.0"
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1"
