[package]
name = "acme_router"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
apollo-router = "1.10.0"
async-trait = "0.1.64"
futures = "0.3.26"
http = "0.2.8"
schemars = "0.8.11"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = "1.25.0"
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1"
