# extends supergraph-demo-fed2/docker-compose.yaml
# https://docs.docker.com/compose/extends/#multiple-compose-files

# use 'make up-supergraph-router-rust-plugin' to get started

version: '3.9'
services:
  apollo-router-rust-plugin:
    container_name: apollo-router-rust-plugin
    build: ./supergraph/router-rust-plugin
    volumes:
      - ./supergraph/router-rust-plugin/router.yaml:/dist/config/router.yaml
    command: [ "--dev", "-c", "config/router.yaml", "--log", "info" ]
    env_file: # 'make up-supergraph-router-rust-plugin' saves APOLLO_KEY and APOLLO_GRAPH_REF to connect to Studio
      - ./graph-api.env
    environment:
      - APOLLO_OTEL_EXPORTER_HOST=collector
    ports:
      - "4000:4000"