# extends supergraph-demo-fed2/docker-compose.yaml
# https://docs.docker.com/compose/extends/#multiple-compose-files

# use 'make up-supergraph-no-otel-local' to get started

version: '3.9'
services:
  apollo-router:
    container_name: apollo-router
    image: ghcr.io/apollographql/router:v1.0.0
    volumes:
      - ./supergraph/schema/docker.graphql:/dist/schema/supergraph.graphql
    command: [ "--dev", "-s", "schema/supergraph.graphql", "--log", "info" ]
    environment:
      - APOLLO_OTEL_EXPORTER_HOST=collector
    ports:
      - "4000:4000"
