name: CI Router Custom Image
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  ci-docker-local:
    name: CI Router Custom Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      -
        name: install rover
        run: |
          echo ---------------------------------------------------------------
          echo rover - installing ...
          echo ---------------------------------------------------------------
          curl -sSL https://rover.apollo.dev/nix/latest | sh -s -- --elv2-license accept
          echo "$HOME/.rover/bin" >> ${GITHUB_PATH}
      -
        name: update docker-compose
        run: |
          which docker-compose && exit 0 || true
          echo ---------------------------------------------------------------
          echo docker-compose - installing ...
          echo ---------------------------------------------------------------
          BIN_DIR=$HOME/.docker-compose/bin
          FILE=$BIN_DIR/docker-compose
          mkdir -p $BIN_DIR
          set -x
          curl -L --fail https://github.com/docker/compose/releases/download/1.29.1/docker-compose-`uname -s`-`uname -m` -o $FILE
          chmod +x $FILE
          echo "downloaded $($FILE --version)"
          echo "$BIN_DIR" >> ${GITHUB_PATH}
          set +x
          echo ---------------------------------------------------------------
      -
        name: check tools
        run: |
          echo ---------------------------------------------------------------
          ( set -x; which rover )
          echo "$(rover --version)"
          echo ---------------------------------------------------------------
          ( set -x; which docker-compose )
          echo "$(docker-compose --version)"
          echo ---------------------------------------------------------------
      - name: make supergraph
        if: false
        run: |
          make supergraph
          cat supergraph.graphql
      - name: docker-compose build
        run: |
          ( set -x; docker-compose -f docker-compose.router-custom-image.yml build --no-cache --pull --parallel --progress plain )
      - name: docker-compose up -d
        run: |
          ( set -x; docker-compose -f docker-compose.router-custom-image.yml  up -d )
          sleep 8
          docker-compose -f docker-compose.router-custom-image.yml logs
      - name: pre debug
        run: |
          docker-compose -f docker-compose.router-custom-image.yml logs
          docker-compose -f docker-compose.router-custom-image.yml ps
      - name: smoke test
        run: .scripts/smoke.sh 4000
      - name: post debug
        if: always()
        run: |
          docker-compose -f docker-compose.router-custom-image.yml logs
          docker-compose -f docker-compose.router-custom-image.yml ps
      - name: docker-compose down
        run: docker-compose -f docker-compose.router-custom-image.yml down
