name: CI Router Managed Federation
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  ci-docker-managed:
    name: CI Router Managed Federation
    runs-on: ubuntu-latest
    env:
      CI: "true"
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF_ROUTER }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      -
        name: install rover
        run: |
          echo ---------------------------------------------------------------
          echo rover - installing ...
          echo ---------------------------------------------------------------
          curl -sSL https://rover.apollo.dev/nix/0.5.0-rc.1 | sh
          echo "$HOME/.rover/bin" >> ${GITHUB_PATH}
      -
        name: update docker-compose
        run: |
          which docker-compose && exit 0 || true
          echo ---------------------------------------------------------------
          echo docker-compose - installing ...
          echo ---------------------------------------------------------------
          BIN_DIR=$HOME/.docker-compose/bin
          FILE=$BIN_DIR/docker-compose
          mkdir -p $BIN_DIR
          set -x
          curl -L --fail https://github.com/docker/compose/releases/download/1.29.1/docker-compose-`uname -s`-`uname -m` -o $FILE
          chmod +x $FILE
          echo "downloaded $($FILE --version)"
          echo "$BIN_DIR" >> ${GITHUB_PATH}
          set +x
          echo ---------------------------------------------------------------
      -
        name: check tools
        run: |
          echo ---------------------------------------------------------------
          ( set -x; which rover )
          echo "$(rover --version)"
          echo ---------------------------------------------------------------
          ( set -x; which docker-compose )
          echo "$(docker-compose --version)"
          echo ---------------------------------------------------------------
      - name: unpublish
        run: |
          make unpublish
      - name: publish
        run: |
          make publish
      - name: docker-compose build
        run: |
          ( set -x; docker-compose -f docker-compose.router-managed.yml build --no-cache --pull --parallel --progress plain )
      - name: docker-compose up -d
        run: |
          ( set -x; docker-compose -f docker-compose.router-managed.yml  up -d )
          sleep 8
          docker-compose -f docker-compose.router-managed.yml logs
      - name: smoke test
        run: .scripts/smoke.sh 4000 250
      - name: docker-compose down
        run: docker-compose -f docker-compose.router-managed.yml down
